flipkart
$('head').prepend('<style type="text/css">	.clip-button {		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #00406e), color-stop(1, #002640) );		background:-moz-linear-gradient( center top, #00406e 5%, #002640 100% );		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr="#00406e", endColorstr="#002640");		background-color:#00406e;		-moz-border-radius:6px;		-webkit-border-radius:6px;		border-radius:6px;		border:1px solid #000000;		display:inline-block;		color:#ffffff;		font-family:"Times New Roman",Georgia,Serif;		font-size:15px;		font-weight:normal;		padding:2px 11px;		text-decoration:none;	}.clip-button:hover {		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #002640), color-stop(1, #00406e) );		background:-moz-linear-gradient( center top, #002640 5%, #00406e 100% );		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr="#002640", endColorstr="#00406e");		background-color:#002640;	}.clip-button:active {		position:relative;		top:1px;	}	/* This imageless css button was generated by CSSButtonGenerator.com */	</style>');
$('.block-body').append('<span style="float:right"><a class="clip-button" style="text-decoration:none">Clip it</a></span>')


craftsvilla
document.getElementsByTagName("head")[0].innerHTML = '<style type="text/css">	.clip-button {		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #00406e), color-stop(1, #002640) );		background:-moz-linear-gradient( center top, #00406e 5%, #002640 100% );		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr="#00406e", endColorstr="#002640");		background-color:#00406e;		-moz-border-radius:6px;		-webkit-border-radius:6px;		border-radius:6px;		border:1px solid #000000;		display:inline-block;		color:#ffffff;		font-family:"Times New Roman",Georgia,Serif;		font-size:15px;		font-weight:normal;		padding:2px 11px;		text-decoration:none;	}.clip-button:hover {		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #002640), color-stop(1, #00406e) );		background:-moz-linear-gradient( center top, #002640 5%, #00406e 100% );		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr="#002640", endColorstr="#00406e");		background-color:#002640;	}.clip-button:active {		position:relative;		top:1px;	}	/* This imageless css button was generated by CSSButtonGenerator.com */	</style>' +document.getElementsByTagName("head")[0].innerHTML;
document.getElementById('socielicon').innerHTML = '<li class="clip"><a href="#" class="clip-button" style="    color: #ffffff;    text-decoration: none;    font-size: 13px;    height: 15px;    line-height: 15px;    padding-right: 0px;    font-weight: normal;">Clip it</a></li>'+ document.getElementById('socielicon').innerHTML;

happilyunmarried
document.getElementsByTagName("head")[0].innerHTML = '<style type="text/css">	.clip-button {		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #00406e), color-stop(1, #002640) );		background:-moz-linear-gradient( center top, #00406e 5%, #002640 100% );		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr="#00406e", endColorstr="#002640");		background-color:#00406e;		-moz-border-radius:6px;		-webkit-border-radius:6px;		border-radius:6px;		border:1px solid #000000;		display:inline-block;		color:#ffffff;		font-family:"Times New Roman",Georgia,Serif;		font-size:15px;		font-weight:normal;		padding:2px 11px;		text-decoration:none;	}.clip-button:hover {		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #002640), color-stop(1, #00406e) );		background:-moz-linear-gradient( center top, #002640 5%, #00406e 100% );		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr="#002640", endColorstr="#00406e");		background-color:#002640;	}.clip-button:active {		position:relative;		top:1px;	}	/* This imageless css button was generated by CSSButtonGenerator.com */	</style>' +document.getElementsByTagName("head")[0].innerHTML;

function prependContentInContainer(matchClass,content) {
    var elems = document.getElementsByTagName('*'), i;
    for (i in elems) {
        if((' ' + elems[i].className + ' ').indexOf(' ' + matchClass + ' ')
                > -1) {
            elems[i].innerHTML = content + elems[i].innerHTML;
        }
    }
}
prependContentInContainer("cart-wishlist", '<a href="#" class="clip-button" style="line-height:18px">Clip it</a> ') ;


itsourstudio:
document.getElementsByTagName("head")[0].innerHTML = '<style type="text/css">	.clip-button {		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #00406e), color-stop(1, #002640) );		background:-moz-linear-gradient( center top, #00406e 5%, #002640 100% );		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr="#00406e", endColorstr="#002640");		background-color:#00406e;		-moz-border-radius:6px;		-webkit-border-radius:6px;		border-radius:6px;		border:1px solid #000000;		display:inline-block;		color:#ffffff;		font-family:"Times New Roman",Georgia,Serif;		font-size:15px;		font-weight:normal;		padding:2px 11px;		text-decoration:none;	}.clip-button:hover {		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #002640), color-stop(1, #00406e) );		background:-moz-linear-gradient( center top, #002640 5%, #00406e 100% );		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr="#002640", endColorstr="#00406e");		background-color:#002640;	}.clip-button:active {		position:relative;		top:1px;	}	/* This imageless css button was generated by CSSButtonGenerator.com */	</style>' +document.getElementsByTagName("head")[0].innerHTML;

function prependContentInContainer(matchClass,content) {
    var elems = document.getElementsByTagName('*'), i;
    for (i in elems) {
        if( ( ' ' + elems[i].className + ' ').indexOf(' ' + matchClass + ' ') > -1 ) {
            elems[i].innerHTML = content + elems[i].innerHTML;
        }
    }
}
prependContentInContainer("addthis_toolbox", '<a style="vertical-align: top; font-size: 14px; height: 15px; padding: 2px 6px; line-height: 14px; color:#ffffff;" class="clip-button" href="#">Clip it</a>') ;



roomstory:
function getElemWithClass(matchClass) {
    var elems = document.getElementsByTagName('*'), i;
    for (i in elems) {
        if( ( ' ' + elems[i].className + ' ').indexOf(' ' + matchClass + ' ') > -1 ) {
        	elems[i].getElementsByTagName("div")[2].setAttribute("style",'margin-left:255px; margin-top:3px;')
            return elems[i].getElementsByTagName("div")[2];
        }
    }
}
document.getElementsByTagName("head")[0].innerHTML = '<style type="text/css">	.clip-button {		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #00406e), color-stop(1, #002640) );		background:-moz-linear-gradient( center top, #00406e 5%, #002640 100% );		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr="#00406e", endColorstr="#002640");		background-color:#00406e;		-moz-border-radius:6px;		-webkit-border-radius:6px;		border-radius:6px;		border:1px solid #000000;		display:inline-block;		color:#ffffff;		font-family:"Times New Roman",Georgia,Serif;		font-size:15px;		font-weight:normal;		padding:2px 11px;		text-decoration:none;	}.clip-button:hover {		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #002640), color-stop(1, #00406e) );		background:-moz-linear-gradient( center top, #002640 5%, #00406e 100% );		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr="#002640", endColorstr="#00406e");		background-color:#002640;	}.clip-button:active {		position:relative;		top:1px;	}	/* This imageless css button was generated by CSSButtonGenerator.com */	</style>' +document.getElementsByTagName("head")[0].innerHTML;
var elem1 = getElemWithClass("imagehold");
elem1.innerHTML = elem1.innerHTML + '<a href="#" class="clip-button" style="color:#ffffff; float:right;line-height: 12px;font-size: 12px;padding: 2px 6px;">Clip it</a>';


fabfurnish
$('head').prepend('<style type="text/css">	.clip-button {		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #00406e), color-stop(1, #002640) );		background:-moz-linear-gradient( center top, #00406e 5%, #002640 100% );		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr="#00406e", endColorstr="#002640");		background-color:#00406e;		-moz-border-radius:6px;		-webkit-border-radius:6px;		border-radius:6px;		border:1px solid #000000;		display:inline-block;		color:#ffffff;		font-family:"Times New Roman",Georgia,Serif;		font-size:15px;		font-weight:normal;		padding:2px 11px;		text-decoration:none;	}.clip-button:hover {		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #002640), color-stop(1, #00406e) );		background:-moz-linear-gradient( center top, #002640 5%, #00406e 100% );		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr="#002640", endColorstr="#00406e");		background-color:#002640;	}.clip-button:active {		position:relative;		top:1px;	}	/* This imageless css button was generated by CSSButtonGenerator.com */	</style>');
$('.add2wish').prepend('<a href="#" class="clip-button" style="color:#ffffff; float:left; line-height:11px;text-decoration: none;padding: 2px 6px;margin-right: 4px;">Clip it</a>') ;

bluestone
$('head').prepend('<style type="text/css">	.clip-button {		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #00406e), color-stop(1, #002640) );		background:-moz-linear-gradient( center top, #00406e 5%, #002640 100% );		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr="#00406e", endColorstr="#002640");		background-color:#00406e;		-moz-border-radius:6px;		-webkit-border-radius:6px;		border-radius:6px;		border:1px solid #000000;		display:inline-block;		color:#ffffff;		font-family:"Times New Roman",Georgia,Serif;		font-size:15px;		font-weight:normal;		padding:2px 11px;		text-decoration:none;	}.clip-button:hover {		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #002640), color-stop(1, #00406e) );		background:-moz-linear-gradient( center top, #002640 5%, #00406e 100% );		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr="#002640", endColorstr="#00406e");		background-color:#002640;	}.clip-button:active {		position:relative;		top:1px;	}	/* This imageless css button was generated by CSSButtonGenerator.com */	</style>');
$(".social-buttons").prepend('<a style="color: rgb(255, 255, 255); float: left; line-height: 12px; padding: 2px 6px; margin-right: 4px; text-decoration: none;" class="clip-button" href="#">Clip it</a>') ;

rangiru
$('head').prepend('<style type="text/css">	.clip-button {		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #00406e), color-stop(1, #002640) );		background:-moz-linear-gradient( center top, #00406e 5%, #002640 100% );		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr="#00406e", endColorstr="#002640");		background-color:#00406e;		-moz-border-radius:6px;		-webkit-border-radius:6px;		border-radius:6px;		border:1px solid #000000;		display:inline-block;		color:#ffffff;		font-family:"Times New Roman",Georgia,Serif;		font-size:15px;		font-weight:normal;		padding:2px 11px;		text-decoration:none;	}.clip-button:hover {		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #002640), color-stop(1, #00406e) );		background:-moz-linear-gradient( center top, #002640 5%, #00406e 100% );		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr="#002640", endColorstr="#00406e");		background-color:#002640;	}.clip-button:active {		position:relative;		top:1px;	}	/* This imageless css button was generated by CSSButtonGenerator.com */	</style>');
$("#product_social_plugins div").prepend('<a href="#" class="clip-button" style="margin-right:5px;font-size:14px;padding: 2px 6px; text-decoration:none;color:#ffffff; float:left; line-height:12px">Clip</a> ');


fetise
$('head').prepend('<style type="text/css">	.clip-button {		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #00406e), color-stop(1, #002640) );		background:-moz-linear-gradient( center top, #00406e 5%, #002640 100% );		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr="#00406e", endColorstr="#002640");		background-color:#00406e;		-moz-border-radius:6px;		-webkit-border-radius:6px;		border-radius:6px;		border:1px solid #000000;		display:inline-block;		color:#ffffff;		font-family:"Times New Roman",Georgia,Serif;		font-size:15px;		font-weight:normal;		padding:2px 11px;		text-decoration:none;	}.clip-button:hover {		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #002640), color-stop(1, #00406e) );		background:-moz-linear-gradient( center top, #002640 5%, #00406e 100% );		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr="#002640", endColorstr="#00406e");		background-color:#002640;	}.clip-button:active {		position:relative;		top:1px;	}	/* This imageless css button was generated by CSSButtonGenerator.com */	</style>');
$('.FetiseTopShare tr').append('<td align="left" class="FetiseTopClip">                                 <a href="#" class="clip-button" style="color:#ffffff; float:left; width:40px;text-align:center;line-height:15px;margin-left:10px ">Clip it</a>                       </td>') ;

urbantouch:
$('head').prepend('<style type="text/css">	.clip-button {		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #00406e), color-stop(1, #002640) );		background:-moz-linear-gradient( center top, #00406e 5%, #002640 100% );		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr="#00406e", endColorstr="#002640");		background-color:#00406e;		-moz-border-radius:6px;		-webkit-border-radius:6px;		border-radius:6px;		border:1px solid #000000;		display:inline-block;		color:#ffffff;		font-family:"Times New Roman",Georgia,Serif;		font-size:15px;		font-weight:normal;		padding:2px 11px;		text-decoration:none;	}.clip-button:hover {		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #002640), color-stop(1, #00406e) );		background:-moz-linear-gradient( center top, #002640 5%, #00406e 100% );		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr="#002640", endColorstr="#00406e");		background-color:#002640;	}.clip-button:active {		position:relative;		top:1px;	}	/* This imageless css button was generated by CSSButtonGenerator.com */	</style>');
$('#add_to_wl').append('<b style="margin-right:3px;margin-left:3px;"> or </b>');
$('#add_to_wl').after('<div><a href="#" class="clip-button" style="margin-top:5px;text-decoration:none;color:#ffffff; float:left; width:40px;text-align:center;line-height:15px;">Clip it</a>                       </div>');




	'<style type="text/css">	.clip-button {		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #00406e), color-stop(1, #002640) );		background:-moz-linear-gradient( center top, #00406e 5%, #002640 100% );		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr="#00406e", endColorstr="#002640");		background-color:#00406e;		-moz-border-radius:6px;		-webkit-border-radius:6px;		border-radius:6px;		border:1px solid #000000;		display:inline-block;		color:#ffffff;		font-family:"Times New Roman",Georgia,Serif;		font-size:15px;		font-weight:normal;		padding:2px 11px;		text-decoration:none;	}.clip-button:hover {		background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #002640), color-stop(1, #00406e) );		background:-moz-linear-gradient( center top, #002640 5%, #00406e 100% );		filter:progid:DXImageTransform.Microsoft.gradient(startColorstr="#002640", endColorstr="#00406e");		background-color:#002640;	}.clip-button:active {		position:relative;		top:1px;	}	/* This imageless css button was generated by CSSButtonGenerator.com */	</style>'
