import printQueryResults
queriesList = []
queriesList.append(('select count(*) as num_registrations from fbdata where accessToken!= ""', "number of registrations"))
queriesList.append(('select count(*) as num_data from fbdata', "number of user data"))
queriesList.append(('select * from affiliateAction order by time desc limit 5', "details of last 5 transactions"))
queriesList.append(('select count(distinct userid, productid) as num_clips from clipsTable', "number of clips"))
queriesList.append(('select count(distinct userid) as num_clippers from clipsTable', "number of clippers"))
queriesList.append(('select firstname, lastname,REPLACE(title,"\n","") from clipsTable as ct join productDetail as pd join fbdata as fd on ct.productid = pd.productid and ct.userid = fd.userid where TIMESTAMPDIFF(SECOND, ct.timestamp,CURRENT_TIMESTAMP) < 3600*24 group by firstname, lastname, title order by ct.timestamp desc', "clips in last day"))
queriesList.append(('select num_clippers/num_registrations*100 as clipperPercent from (select count(distinct userid) as num_clippers from clipsTable) as clipper,(select count(*) as num_registrations from fbdata where accessToken!= "") as registerer;', "percent of clippers"))
queriesList.append(('select 100*good/total as interestsEntered from  (select count(distinct userid) as good from interestsTable where userid = source) as interests , (select count(distinct userid) as total from fbdata where accessToken != "") as fb;',"percent of users who have entered interests"))
queriesList.append(('select count(distinct userid, productid) as num_tags from tagTable', "number of tags"))
queriesList.append(('select count(distinct userid, productid, taggeduser) as num_tags_posted from tagTable', "number of tags posted"))
queriesList.append(('select count(distinct userid) as num_taggers from tagTable ', "number of people who tagged atleast once"))
queriesList.append(('select tagTable.productid, CONCAT(fbdata.firstname," ",fbdata.lastname) as name  from tagTable join fbdata on tagTable.userid = fbdata.userid where TIMESTAMPDIFF(SECOND, timestamp, CURRENT_TIMESTAMP)<3600*24', "products and taggers in last 24 hours"))
queriesList.append(('select userid, firstname, lastname, email from fbdata where userid in (select userid from (select userid, min(time) as mintime from loginActivity group by userid having TIMESTAMPDIFF(SECOND, mintime,CURRENT_TIMESTAMP) < 3600*24) as tempTable) order by userid', "people registered in last day"))
queriesList.append(('select loginActivity.userid, firstname, lastname, loginActivity.time from loginActivity join fbdata on fbdata.userid=loginActivity.userid where TIMESTAMPDIFF(SECOND, loginActivity.time,CURRENT_TIMESTAMP) < 3600*24 order by loginActivity.time desc',"users that logged-in in last day"))
queriesList.append(('select count(distinct userid) as numLogins from loginActivity where TIMESTAMPDIFF(SECOND, loginActivity.time,CURRENT_TIMESTAMP) < 3600*24',"number of users that logged-in in last day"))
queriesList.append(('select count(distinct userid) as numLogins from loginActivity where TIMESTAMPDIFF(SECOND, loginActivity.time,CURRENT_TIMESTAMP) < 3600*24*15',"number of users that logged-in in last 15 days"))
queriesList.append(('select count(distinct userid) as numLogins from loginActivity where TIMESTAMPDIFF(SECOND, loginActivity.time,CURRENT_TIMESTAMP) < 3600*24*30',"number of users that logged-in in last 30 days"))
queriesList.append(('select count(*) from productDetail', "number of products"))
queriesList.append(('select siteId, count(*) from productDetail group by siteId', "number of products per site"))
queriesList.append(('select count(distinct productid) from addedProduct where userid!=0', "number of times products were added through site"))
queriesList.append(('select count(distinct productid) from addedProduct where userid!=0 and repeatadd=0', "number of unique products added through site"))
queriesList.append(('select groupname, count(distinct productid) from productGroup join groupTable on groupTable.id=productGroup.groupid group by groupname', "number of products per group"))
queriesList.append(('select allTags.name, count(distinct productid) from cliprTagTable join allTags on allTags.id=cliprTagTable.cliprTag group by allTags.name', "number of products per interest"))
queriesList.append(('select pv.productid, REPLACE(title,"\n",""), siteId, price, coalesce(sum(views),0) as totalviews from productView as pv join productDetail as pd on pd.productid = pv.productid group by pv.productid order by totalviews desc limit 5',"most viewed products"))
queriesList.append(('select firstname, lastname, ap.link, ap.productid from addedProduct as ap join fbdata as fd on ap.userid = fd.userid where ap.userid > 0 group by ap.userid,productid order by ap.time desc limit 10',"products added from website"))
printQueryResults.printResults(queriesList)